name: Deploy pihole6_exporter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Prepare files
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing current directory:"
          ls -la
          
          echo "Creating deploy_files directory..."
          mkdir -p deploy_files
          
          echo "Copying files to deploy_files..."
          cp pihole6_exporter deploy_files/ || { echo "Failed to copy pihole6_exporter"; exit 1; }
          cp pihole6_exporter.service deploy_files/ || { echo "Failed to copy service file"; exit 1; }
          cp requirements.txt deploy_files/ || { echo "Failed to copy requirements.txt"; exit 1; }
          
          echo "Listing deploy_files directory:"
          ls -la deploy_files/
          
      - name: Create target directory on Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PIHOLE_HOST }}
          username: ${{ secrets.PIHOLE_USER }}
          key: ${{ secrets.PIHOLE_SSH_KEY }}
          script: |
            sudo mkdir -p /tmp/pihole6_exporter
            sudo chmod 777 /tmp/pihole6_exporter
          
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PIHOLE_HOST }}
          username: ${{ secrets.PIHOLE_USER }}
          key: ${{ secrets.PIHOLE_SSH_KEY }}
          source: "deploy_files"
          target: "/tmp/pihole6_exporter"
          script: |
            set -e  # Exit on any error
            
            # List files to verify they were copied
            ls -la /tmp/pihole6_exporter/
            
            # Copy the exporter script
            sudo cp /tmp/pihole6_exporter/pihole6_exporter /usr/local/bin/ || { echo "Failed to copy pihole6_exporter"; exit 1; }
            sudo chmod +x /usr/local/bin/pihole6_exporter || { echo "Failed to make pihole6_exporter executable"; exit 1; }
            
            # Set up the service
            sudo cp /tmp/pihole6_exporter/pihole6_exporter.service /etc/systemd/system/ || { echo "Failed to copy service file"; exit 1; }
            sudo systemctl daemon-reload || { echo "Failed to reload systemd"; exit 1; }
            sudo systemctl enable pihole6_exporter || { echo "Failed to enable service"; exit 1; }
            
            # Install dependencies
            sudo pip3 install -r /tmp/pihole6_exporter/requirements.txt || { echo "Failed to install dependencies"; exit 1; }
            
            # Restart the service
            sudo systemctl restart pihole6_exporter || { echo "Failed to restart service"; exit 1; }
            
            # Clean up
            rm -rf /tmp/pihole6_exporter
            
            echo "Deployment completed successfully" 