name: Deploy pihole6_exporter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PIHOLE_HOST }}
          username: ${{ secrets.PIHOLE_USER }}
          key: ${{ secrets.PIHOLE_SSH_KEY }}
          script: |
            cd /opt/pihole_exporter
            git pull
            pip install -r requirements.txt
            sudo systemctl restart pihole6_exporter 