name: Deploy pihole6_exporter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PIHOLE_HOST }}
          username: ${{ secrets.PIHOLE_USER }}
          key: ${{ secrets.PIHOLE_SSH_KEY }}
          script: |
            # Create directory if it doesn't exist
            sudo mkdir -p /usr/local/bin
            
            # Copy the exporter script
            sudo cp pihole6_exporter /usr/local/bin/
            sudo chmod +x /usr/local/bin/pihole6_exporter
            
            # Set up the service
            sudo cp pihole6_exporter.service /etc/systemd/system/
            sudo systemctl daemon-reload
            sudo systemctl enable pihole6_exporter
            
            # Install dependencies
            sudo pip3 install -r requirements.txt
            
            # Restart the service
            sudo systemctl restart pihole6_exporter 