name: Deploy pihole6_exporter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ───────────────────────────────────────────────────────────────
    # 1)  Check out repository
    # ───────────────────────────────────────────────────────────────
    - name: Checkout code
      uses: actions/checkout@v4

    # ───────────────────────────────────────────────────────────────
    # 2)  Stage the files we want to copy to the Pi
    # ───────────────────────────────────────────────────────────────
    - name: Build deploy bundle
      run: |
        mkdir -p deploy_files
        cp pihole6_exporter.py deploy_files/
        cp pihole6_exporter.service   deploy_files/
        cp requirements.txt           deploy_files/

    # ───────────────────────────────────────────────────────────────
    # 3)  Secure-copy the bundle to the Raspberry Pi
    # ───────────────────────────────────────────────────────────────
    - name: Copy files to Raspberry Pi
      uses: appleboy/scp-action@v1
      with:
        host:     ${{ secrets.PIHOLE_HOST }}
        username: ${{ secrets.PIHOLE_USER }}
        key:      ${{ secrets.PIHOLE_SSH_KEY }}
        source:   "deploy_files"          # send the whole folder
        target:   "/tmp/pihole6_exporter"
        strip_components: 1               # drop the leading "deploy_files/" dir
        rm:       true                 # clean target dir before upload

    # ───────────────────────────────────────────────────────────────
    # 4)  Ensure pip3 + venv prerequisites
    # ───────────────────────────────────────────────────────────────
    - name: Ensure Python prerequisites
      uses: appleboy/ssh-action@v1
      with:
        host:     ${{ secrets.PIHOLE_HOST }}
        username: ${{ secrets.PIHOLE_USER }}
        key:      ${{ secrets.PIHOLE_SSH_KEY }}
        script: |
          set -e
          echo "🛠  Installing python3-pip / python3-venv if missing…"
          sudo apt-get update -qq
          if ! command -v pip3 >/dev/null 2>&1; then
            sudo apt-get install -y python3-pip
          fi
          sudo apt-get install -y python3-venv

    # ───────────────────────────────────────────────────────────────
    # 5)  Install the binary and systemd unit
    # ───────────────────────────────────────────────────────────────
    - name: Install exporter binary and unit file
      uses: appleboy/ssh-action@v1
      with:
        host:     ${{ secrets.PIHOLE_HOST }}
        username: ${{ secrets.PIHOLE_USER }}
        key:      ${{ secrets.PIHOLE_SSH_KEY }}
        script: |
          set -e
          echo "📂 Installing binary & systemd unit…"
          sudo install -m 755 /tmp/pihole6_exporter/pihole6_exporter.py /usr/local/bin/pihole6_exporter
          sudo install -m 644 /tmp/pihole6_exporter/pihole6_exporter.service /etc/systemd/system/

    # ───────────────────────────────────────────────────────────────
    # 6)  Create / refresh virtual-env and install Python deps
    # ───────────────────────────────────────────────────────────────
    - name: Create/update virtual environment
      uses: appleboy/ssh-action@v1
      with:
        host:     ${{ secrets.PIHOLE_HOST }}
        username: ${{ secrets.PIHOLE_USER }}
        key:      ${{ secrets.PIHOLE_SSH_KEY }}
        script: |
          set -e
          echo "🐍 Setting up virtual environment…"
          sudo install -d /opt/pihole6_exporter
          sudo python3 -m venv /opt/pihole6_exporter/venv
          sudo /opt/pihole6_exporter/venv/bin/python -m pip install --upgrade pip
          sudo /opt/pihole6_exporter/venv/bin/pip install --no-cache-dir -r /tmp/pihole6_exporter/requirements.txt

    # ───────────────────────────────────────────────────────────────
    # 7)  Reload systemd, enable & restart service, clean up tmp dir
    # ───────────────────────────────────────────────────────────────
    - name: Reload & restart service, clean up
      uses: appleboy/ssh-action@v1
      with:
        host:     ${{ secrets.PIHOLE_HOST }}
        username: ${{ secrets.PIHOLE_USER }}
        key:      ${{ secrets.PIHOLE_SSH_KEY }}
        script: |
          set -e
          echo "🔄 Reloading systemd & restarting service…"
          sudo systemctl daemon-reload
          sudo systemctl enable pihole6_exporter
          sudo systemctl restart pihole6_exporter
          echo "📊 Checking service status…"
          sudo systemctl status pihole6_exporter --no-pager
          echo "🧹 Cleaning up /tmp files…"
          rm -rf /tmp/pihole6_exporter
          echo "✅ Deployment completed successfully."
